Data's transformation and analysis of sentiments
Pamelabu/trip_advisor pull request #1
Opened 2023-06-18 10:57 UTC by Pamelabu

2023-06-18 11:04 UTC, PiotrSkoupy requested changes

2023-06-18 11:04 UTC, PiotrSkoupy commented on main.py
> -    print(len(more_buttons))
Usuń komentarze i printy

2023-06-20 09:40 UTC, Pamelabu commented on main.py
> -    print(len(more_buttons))
Done

2023-06-20 16:27 UTC, PiotrSkoupy approved these changes

2023-06-20 16:27 UTC, merged